### ISSUE TITLE
May I ask where is the appendix of the paper?

### ISSUE THREAD

**Issue by JackWoo0831** [alibaba/u2mot#1]
Many thanks for your outstanding work. 

Could you open your appendix? Particularly I wonder how the reid head is designed. 

Also, it seems that I cannot find the code of reid and trajectory-guided augmentation..

**Comment by JackWoo0831** [comment]
Alright, I have found the appendix~

**Comment by kail8** [comment]
Thanks for your attention! For ReID head, please refer to https://github.com/alibaba/u2mot/blob/7411211d17cb893f5fcd6be39cd4e5f91cfe1586/yolox/models/yolo_head.py#L140  and for TGA, please refer to https://github.com/alibaba/u2mot/blob/7411211d17cb893f5fcd6be39cd4e5f91cfe1586/yolox/data/datasets/mot.py#L240
