### ISSUE TITLE
eval result on visdrone test set when using VisDrone2018-MOT-toolkit

### ISSUE THREAD

**Issue by RenLibo-aircas** [alibaba/u2mot#2]
Hello, I really like your paper, but I have a question. Regarding the validation script on the VisDronedataset, are you using the py-motmetrics library for validation instead of the official VisDrone matlab toolkil？(https://github.com/VisDrone/VisDrone2018-MOT-toolkit) I tested your model and obtained an MOTA of 55.9, but when using the MATLAB library, the MOTA is only 50.2. It seems that there may be some differences in the validation process between the two libraries, and I haven't found the reason.

**Comment by kail8** [comment]
Sorry for the late reply. I am working on LLM and MLLM now, and I am losing some details of this paper. But it seems we did use the py-motmetrics library for evaluation to align with other MOT datasets in this repo. We will update the results with the VisDrone toolkit if available.
