### ISSUE TITLE
How to train on unlabeled data?

### ISSUE THREAD

**Issue by siddtmb** [alibaba/u2mot#3]
How can we train on unlabeled custom data? Your instructions mentioned that we have to convert the dataset to COCO annotations, but I don't have track ID labels for my task; I have the bounding boxes from Yolo. 

Please let me know. Thanks.

**Comment by kail8** [comment]
Sorry for the late reply. Just set your ID labels to -1, and our code will ignore the IDs and generate the pseudo-labels automatically.
