### ISSUE TITLE
where is the reid model?

### ISSUE THREAD

**Issue by bdpk123** [alibaba/u2mot#4]
Hello, thank you very much for your work, could you tell me which part of the system you are using for the re-identification (REID) module?

**Comment by bdpk123** [comment]
Could you provide a detailed explanation about this re-identification (REID) model?

**Comment by kail8** [comment]
Hi, thanks for your attention. In U2MOT, we actually do not use a separate ReID model. We merely add several conv layers on top of the model backbone. You can find the details in: https://github.com/alibaba/u2mot/blob/7411211d17cb893f5fcd6be39cd4e5f91cfe1586/yolox/models/yolo_head.py#L140
